### ISSUE TITLE
rotate or tilt in leaflet?

### ISSUE THREAD

**Issue by MagyAndy** [OSMBuildings/OSMBuildings#143]
Hi, I wonder if we can complete the rotation or tilt in using leaflet? As far as I know, it can achieve in 
 GLMap.

I saw the new version 3.2.4, you said the 'rotation is now controlled by mouse button 2', I try, and it is wonderful.

**Comment by kekscom** [comment]
Hi, The effort would be huge and heavily dependent on Leaflet changes.
This should be left to GL renderers.

Thank you for the compliments!


Am 03.09.2017 um 05:23 schrieb MagyAndy <notifications@github.com>:

Hi, I wonder if we can complete the rotation or tilt in using leaflet? As far as I know, it can achieve in
GLMap.

I saw the new version 3.2.4, you said the 'rotation is now controlled by mouse button 2', I try, and it is wonderful.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.



Viele Grüße
Jan Marsch

**Comment by MagyAndy** [comment]
so, what's your meaning about GL renderers?

it is Mapbox GL(https://www.mapbox.com/) or
 the GLMap in the OSMBuildings/GLMap  (https://github.com/OSMBuildings/GLMap )?

**Comment by kekscom** [comment]
Both are good options.
I'd also add Mapzen's Tangram as a Leaflet/WebGL hybrid solution.

**Comment by MagyAndy** [comment]
Wow,  I seem to open a gate to new world.
