### ISSUE TITLE
roof:shape=gabled and roof:direction

### ISSUE THREAD

**Issue by sorcrosc** [OSMBuildings/OSMBuildings#197]
I think OSM Buildings is not evaluating correctly roof:direction for gabled roof type.
Right now the direction it takes as roof:direction is the ridge direction, instead it should be the slope direction. Basically it should be the same as for skillion roof type, which is well interpreted.

Here is documentation for roof:direction. Example picture does not include gabled type but a gabled_row is present:
https://wiki.openstreetmap.org/wiki/Key:roof:direction

Other source probably useful:
https://wiki.openstreetmap.org/wiki/Talk:Simple_3D_buildings#roof_direction

I came into this while mapping entrances on buildings. Putting extra nodes on the sides often cause longest side to be split in two or more. In this situation using roof:orientation=along/across is a mess and result become unpredictable. Using roof:direction with angle value should be much stronger.

Hope it's clear what I wrote.

Thanks

**Comment by kekscom** [comment]
Hi,
I finally had a look into this.
Unfortunately the wiki shows no clear standard for this and discussion seems to be stale.
Authors tend to tagging roof face directions rather than ridges. This is not intuitive at all.
Given that, OSM Buildings is indeed not following this, let's say, draft.

I'd be open for discussion if you could provide examples where this is really counter productive.

However, thank you for bringing this up.

**Comment by natrius** [comment]
In my opinion it should be treated with slope-direction and not ridge-direction. roof:orientation is the ridge, thats clear. 

According to https://wiki.openstreetmap.org/wiki/Key:roof:direction there is saltbox and saltbox can be treated as gabled in this case. I'm asking myself why they did not include gabled as it will be one of the most used ones, but yeah. 

I actually like this and may use this instead of roof:orientation=across because its clear whats meant.  Kendzi is treating SE as a general thing like along/across and an numeric angle as absolute value.

roof:orienteation=SE
![grafik](https://user-images.githubusercontent.com/7243447/81391510-7e769080-911d-11ea-9743-0bf917f91616.png)

roof:orientation=135
![grafik](https://user-images.githubusercontent.com/7243447/81391541-8afae900-911d-11ea-9ba3-f8dabd2a24b5.png)

It should work as in the wiki and in my opinion it is showing clear.

**Comment by kekscom** [comment]
Could you post the osm id of this building?

**Comment by kekscom** [comment]
found it: https://osmbuildings.org/?lat=47.82902&lon=13.05415&zoom=20.0&tilt=6&rotation=-43
osm id: 97255541

**Comment by natrius** [comment]
Yepp, you found it. It was just to show it in the screens, that i did not think about that. 

You are correct, i meant direction (corrected now in the last post). 
Well, it seems to me Kendzi is interpreting it like its in the screenshot. SE more like a general thing so you can align it somewhat properly in an easy way. And if you have specific need, you should use angle.  Why do i think so? Because South-East (SE) is basically 135° . So at least kendzi is treating it differently. I don't know about f4maps.

**Comment by kekscom** [comment]
I'm considering this behavior:
1. If roof:direction is tagged as angle, use it like roof face direction (according to the wiki).
2. If no roof:direction is tagged, determine building orientation (equivalent to ridge direction of gabled roofs). Use the perpendicular as roof:direction.
3. if roof:direction is tagged as letters N,E,S,W... these are snapped to building orientation and then treated as roof face direction (according to the wiki).

**Comment by sorcrosc** [comment]
It looks good to me!

**Comment by kekscom** [comment]
Server and OSM Buildings are updated. Please verify (v4.1.0+).

**Comment by kekscom** [comment]
What about this @natrius ?

**Comment by sorcrosc** [comment]
As for directions, they are as I expected and nice. Thank you.

I see contours of some buildings kind of simplified like this:
![immagine](https://user-images.githubusercontent.com/7443746/83635417-7ab31e00-a5a4-11ea-8275-83f0d80277c3.png) ![immagine](https://user-images.githubusercontent.com/7443746/83635929-586dd000-a5a5-11ea-8ac3-da495669d8e8.png)

Also, buildings with roof:shape=round appear with no roof (I see inside).

Is this expected?

**Comment by kekscom** [comment]
Simplification is expected and necessary but not that much.
Missing round roofs seem odd. Do you have examples?
OSM / OSMB urls are always welcome.

**Comment by sorcrosc** [comment]
here are the links:

https://osmbuildings.org/?lat=43.84174&lon=13.01685&zoom=20.0&tilt=40&rotation=56
https://www.openstreetmap.org/way/525266951

https://osmbuildings.org/?lat=43.84629&lon=13.01408&zoom=20.0&tilt=28&rotation=90
https://www.openstreetmap.org/way/488339118

**Comment by kekscom** [comment]
Thanks.
Both are fixed now. v4.1.1

**Comment by natrius** [comment]
Its seems like the 'general' one is not working anymore. https://www.openstreetmap.org/way/957595306 here is using `roof:direction=SSE` what should be the correct one according to https://wiki.openstreetmap.org/wiki/Key:roof:direction and osmbuildings outputs `roofDirection=151.10000000000002`

Did i do something wrong?
