### ISSUE TITLE
Has OSMBuildings ceased development?

### ISSUE THREAD

**Issue by hb0nd** [OSMBuildings/OSMBuildings#252]
Reading about the Cesium situation and the fact that there have been no changes for two years, is it safe to say that this project is not going to be worked on anymore? :(

**Comment by kekscom** [comment]
Hey, Thank you for your thoughts. It's not yet safe to consider it stopped.

**Comment by EvanCarroll** [comment]
@kekscom I would be interested in more information. From the documentation on the site the answer seems like "yes". The community effort is dead because it was stolen/taken by a large corporation.

If not, under what terms does development continue here? Is there someone that doesn't agree with the published statement and will evaluate code/patches when submitted (there seems to be a lot of forks with code).

I would also be interested in why this wasn't just forked into a community driven one where you (or another dev owns the Trademarks). This is normally what happens,

* Company takes over open source project.
* Open Source project Trademarks new name, forks code and continues.

LineageOS, Ice Weasel, LibeOffice etc. They all do this. Maybe this is the route forward?

Not OSM Buildings, "OSM LibreStreet 3D"?
