### ISSUE TITLE
z-fighting on some buildings

### ISSUE THREAD

**Issue by brianchirls** [OSMBuildings/OSMBuildings#27]
I'm seeing z-fighting in some buildings, usually ones that are more complex, such as the one at the base of this tower in Berlin:
http://osmbuildings.org/?lat=52.52108&lon=13.40914&zoom=18&rotation=4&tilt=36

I'm seeing it in London and [New York](http://osmbuildings.org/?lat=40.76062&lon=-73.97993&zoom=17.6&rotation=4&tilt=30&q=10019) as well. I suspect this is possibly the result of duplicate triangles. I don't know if the duplicates are in the incoming tile data or created client-side.

**Comment by kekscom** [comment]
Yes, tehre are duplicate polygons.
This is due to tagging in OSM which needs better interpratation on OSM Buldings side.

**Comment by brianchirls** [comment]
Do you think this is something we can detect and correct for in the client-side building construction code?

**Comment by kekscom** [comment]
Looks really like a server side fix. I'll touch that anyway within few days.

**Comment by brianchirls** [comment]
Great. Thanks.

Is this the right place to submit server-related issues?

**Comment by kekscom** [comment]
Absolutely.

**Comment by brianchirls** [comment]
I wonder if you've had any time to look at this, @kekscom.

I took a shot at eliminating duplicate polygons on the client side but haven't had any luck. Thanks again.

**Comment by rbuch703** [comment]
Hi @brianchirls. The problem is that what you are seeing are not duplicate OSM polygons. Most of the z-fighting in OSMBuildings comes from OSM polygons that share a single edge, and so their 3D counterparts have some overlapping faces. The reason is usually that a single building is present in OSM in two different levels of details: as a single low-detail building=* and as a number of building:part=* entities (ways or multipolygons). If both are rendered at the same time, you'll get the z-fighting issues you reported. Unfortunately it is non-trivial to separate the two.

**Comment by brianchirls** [comment]
Well, it's super helpful to at least have an explanation of what the problem is. So, thank you.

Would it make sense to eliminate a building entry if it also has parts matching the same id? Or I wonder if maybe as a temporary hack, I could slightly offset geometry of a part...or use polygon offsets?

**Comment by kekscom** [comment]
Hi @brianchirls, for rendering @rbuch703's points are very valid.
I also need to look into server side code in order to eliminate a few polygon duplications.
Unfortunately I had no time to do this until now.
I'll try again within next days.
Thanks for being super patient so far!

**Comment by brianchirls** [comment]
@kekscom: I appreciate any effort. I'm only asking again now, as we have to demo a prototype of something soon.

**Comment by rbuch703** [comment]
@brianchirls: in that case let me give you a few more details on the issue and what you might be able to do yourself to mitigate the z-fighting.

As I explained above, the z-fighting in OSM data is usually caused by building detail geometry (building:part=*) overlapping with an actual building. Now, the OSM Simple 3D Buildings specification at http://wiki.openstreetmap.org/wiki/Simple_3D_buildings defines two different approaches on how to handle this situation:

1. any renderer (including OSMBuildings) should ignore buildings that overlap with at least one building:part
2. OSM contributors may define building **relations** (not to be confused with building **ways** or **multipolygons relations** with building attributes). A building relation references an actual OSM building (a building way or building multipolygon relation) using the 'outline' role as well as all building parts (again as ways or multipolygons) using the 'part' role to represent the detail geometry of that building. Renderers can then use this information to decide whether to render the coarse or the detail geometry, and thus avoid rendering both and causing z-fighting.

Now it is unlikely that OSMBuildings will support Approach 1 any time soon, as it is quite complicated to implement it to run fast and reliably at the same time. However, the OSMBuildings backend **already** partially supports Approach 2: it correctly handles building relations when both the building outline as well as all building parts are ways (as opposed to multipolygon relations).

For example see relation https://www.openstreetmap.org/relation/6025376 , which ties together the building way https://www.openstreetmap.org/way/269098580 and a number of building:part ways. And even though the building and its parts overlap, due to the building relation OSMBuildings manages to render the building correctly without z-fighting (see http://osmbuildings.org/?lat=52.44885&lon=13.34827&zoom=19.4&rotation=0&tilt=30 ).

So depending on the type of data you need in your prototype, you may be able to add building relations to OSM to fix your z-fighting issues without relying on @kekscom to modify the OSMBuildings backend. (Please note though that the OSMBuildings backend caches geometry data, so your new building relations will not be reflected instantaneously in the OSMBuildings JSON responses or the render output.)

**Comment by kekscom** [comment]
Part 2. Should work much better now.

**Comment by kekscom** [comment]
Part 1, the overlapping test is in place now.
