### ISSUE TITLE
Bower support

### ISSUE THREAD

**Issue by etabard** [OSMBuildings/OSMBuildings#35]
Hi, thanks for this great project ! Could you please add the bower support : http://bower.io/docs/creating-packages/

It's easier for developers to install and update javascript dependencies 

Thanks again

**Comment by kekscom** [comment]
Hi, I don't see a chance at the moment. Mostly because I can't stem the effort to support and - more important - to maintain various package managers.
AFAIK should be possible to point bower directly to github or better, to a specific release zip file.
Regards

**Comment by etabard** [comment]
Fair enough ! It is possible to point bower directly to github but the dist folder doesn't include the built file.
Thanks again for this great lib

**Comment by dkniffin** [comment]
@etabard fyi, I'm working on getting a bower package set up for OSMBuildings (#52)

**Comment by kekscom** [comment]
I could live with a dist file. Also seems many users struggling with Github's release system.
I think @rbuch703 would be less happy about it. Anybthoughts?

**Comment by rbuch703** [comment]
Yeah, I'd like to keep auto-generated stuff out of the main OSMBuildings repository as it clutters the repository (a `git clone` always downloads all versions of all files from the repository) and can easily lead to inconsistencies within the repository (where something is already changed/fixed in the "actual" source code, but the `dist` files are still in an older state).

But how about having a separate repository for the bower package? By itself it would only contain the bower config and the dist folder. It could link to the main OSMBuildings repository as a `git`'s `submodule` in order to update it's `dist` files.

**Comment by dkniffin** [comment]
@rbuch703 I mean, we _could_ do that, but that's just going to be one more thing to keep up with, and it will probably confuse developers who come looking for the package.

What you're talking about with `git clone` keeping all versions is only if the version is in the filename, which it doesn't need to be. We could just have a `dist/OSMBuildings.js` (and `.debug.js`, `.css`, etc).

It's up to you guys how you want to do it, but looking at some other front-end libraries, such as [bootstrap](https://github.com/twbs/bootstrap), [moment](https://github.com/moment/moment), [three.js](https://github.com/mrdoob/three.js), and others, they all just keep a compiled version in the repo. Going with this de-facto standard way of doing it would also probably alleviate some confusion by users who come looking for things.

**Comment by kekscom** [comment]
I have 2 objectives, by priority:
1. make it as easy as possible for developers to get started with the library
2. make our development easy

Bower is no priority for me and a potential source of maintenance. 
If it's as simple as @dkniffin said, I'm fine with the PR. 

Regarding dist files:
There should be no build done outside master branch. There is one task creating the shader code. I'll make that the default build action..
Release builds on master will be part of the repo again. I'd sa with constant name in order to keep file count low.
I also opt for a CI hook, I.e. Travis that could trigger builds on master. 
As an option, versions builds could be pushed to a CDN. I'll need more info how to do that.

Could you agree with that?

**Comment by rbuch703** [comment]
I'm okay with @kekscom's proposal to have the dist files in the repository again, but only update them when the master branch is updated. We may have to start setting up development guidelines to communicate this policy to contributors to make it effective, though. And I'd keep the dist folder in the `.gitignore` file to prevent/reduce accidental updates of the dist files (and I'd add this reasoning as a comment to `.gitignore`).

For the record, I think it is terrible development practice to have manually written and auto-generated files in the same repository. But I agree with @dkniffin that this seems to be currently prevalent and expected in the Javascript development community.

@dkniffin: about `git clone`: this command downloads and stores not just the current repository snapshot, but every version of every file ever created in the repository. So it will indeed download every version of the dist files *no matter* whether they have different file names or if its just one file overwritten over and over again (even though in the latter case you'll see just one file outside of the `.git` folder).

**Comment by kekscom** [comment]
The unclear thing for me is, once someone does a build on master (which is fine), how would they push it? Assuming dist is in .gitignore.

Just had a look into Travis CI. Looks it won't push either as it respects .gitignore too.
However, it can upload somewhere else which gets us closer to CDN.

**Comment by dkniffin** [comment]
@kekscom It looks like it's possible via [`--force`](http://stackoverflow.com/a/8006450/1202488). This is still kind a weird pattern to me, but I guess I see the reasoning.

**Comment by rbuch703** [comment]
And in that gist you linked, travis is configured to manually push to a repo using arbitrary git commands. This way, we should also be able to tell travis to bypass the `.gitignore` file via `git add --force`.

**Comment by kekscom** [comment]
It already builds automatically. So I'm confident it's possible just to add the force push.

**Comment by rbuch703** [comment]
A positive side-effect of having the dist files in the repository is that we will be able to use http://rawgit.com as a CDN without any additional setup (or fees). URLs like https://cdn.rawgit.com/OSMBuildings/OSMBuildings/v2.3.1/dist/OSMBuildings/skydome.jpg just work out-of-the-box.

**Comment by dkniffin** [comment]
@kekscom I was going to make a PR to try and finish this up, but I think you'll need to to do it, because it'll require creating a [travis token](https://gist.github.com/domenic/ec8b0fc8ab45f39403dd#get-encrypted-credentials)

**Comment by kekscom** [comment]
I'll take care of that. Just super busy today.
Many nice things to come :-)

**Comment by kekscom** [comment]
- bower.json is finally in place. @dkniffin please check whether it works.
- Travis config is updated with token

**Comment by dkniffin** [comment]
Alright, I've got another PR open (#80), with a few more changes. After that, we should be pretty close to having a bower package.

**Comment by kekscom** [comment]
Great work! Thanks for that
