### ISSUE TITLE
Terrain Data

### ISSUE THREAD

**Issue by hrishiballal** [OSMBuildings/OSMBuildings#39]
I know this may be out of scope of this project but is there any way that terrain data can be added to OSMB?

**Comment by kekscom** [comment]
It's not far off. However I don't have the resources yet to make it happen.

**Comment by hrishiballal** [comment]
Just for my understanding, can I ask how it will work?

**Comment by kekscom** [comment]
It would need elevation data that has likely to be pulled in as tiles.
Then a 3d mesh will be generated which is finally just another object.
At the end, buildings have to be placed at correct altitude. Also respecting terrain rarely cuts buildings in a horizontal line.
All doable and a much better impression.

**Comment by dkniffin** [comment]
I would love to see terrain support in osmbuildings. I worked on this in a project a while back. If I remember correctly, I got the terrain part working, but I abandoned the project before getting the buildings and roads and such working completely. Here's the source code for the terrain part: https://github.com/dkniffin/Berries/blob/master/src/worker/generateTerrain.js Feel free to copy anything from there, if it helps.

Also, I'm thinking about using this library in a game I'm working on. If that happens, I will probably make some PRs to this project, and it may include this feature.

**Comment by kekscom** [comment]
Thanks, this looks like a good starting point.
Still not sure how ti place buildings.
Many just extend them down to elevation 0 but I'm not sure whether thats good with textures and vertical shading.

**Comment by dkniffin** [comment]
Yea, the way I handled it was not very good. I simply took the first node in the way, and found the height of the terrain from that point, and start the building there. So in mine, I had air gaps under some of my buildings.

I just looked through the tagging spec, and I _thought_ there was mention of where building:levels starts (ie: the lowest point or highest) on [this page](https://wiki.openstreetmap.org/wiki/Key:building:levels) but the only place I can find it is in the discussion. I may edit it at some point.

But...assuming building:levels and/or height _does_ start from the lowest, above-ground point: we can loop over the nodes, and find the elevation of each one on the terrain, and make that the starting point. A little bit of the geometry will be below ground, but not much.

If it turns out that the height is calculated from the highest point, then we could do almost the same thing, except that the height would have to account for the offset between the lowest point on the building and the highest.

Hopefully that makes sense. This isn't the easiest thing to describe in words :stuck_out_tongue:

**Comment by kekscom** [comment]
The definition you refer to and common sense point to solution with starting from lowest point on footprint. Not sure that covers very large (area) buildings on very distorted terrain.
However, its perhaps edge cases.

**Comment by rbuch703** [comment]
Just to weigh in, I'm not too concerned with vertical building placement. For a first version, it doesn't have to be perfect to be usable. I'd say most cities are almost flat at the scale of buildings footprints, so any errors wouldn't be that badly visible. And later, we could implement more advanced algorithms that precompute good vertical building placements on the server-side and add them as GeoJSON attributes to each building to reduce client-side overhead. 

I'm more concerned with other issues:

- is there a suitable data source, e.g. a freely usable *tileset* of worldwide heightmap tiles from SRTM using - preferably - the same map projection as we do? This date source would also have to provide different zoom levels for geometric level-of-detail

- was the dataset processed to reflect *terrain* heights as opposed to *apparent surface* heights? Without this processing, the height data would confuse heights from hills and buildings. This is adequate for some applications, but would mess up the height data for cities, exactly those areas that we want to visualize

- which parts of OSMBuildings rely on a flat map layer and would have to be reworked completely to support terrain rendering? Some that come to mind are 

  - computation of the set of visible basemap tiles and their zoom level (and anything else that depends on the view trapezoid)
  - rendering of the basemap tiles (currently, each can be rendered independently and is just a quad)
  - shadow mapping parameters set to minimize shadow artifacts (e.g. fading out the shadows when the sun is low over the horizon)
  - SSAO on the basemap (it is currently rendered as an overlay over an invisible flat map, to allow for basemap layers that are rendered independently of OSMBuildings - such as MapBoxGL)

So I'm all for experiments to get terrain rendering into OSMBuildings. But to reach production quality would be time-consuming, and it'd take quite some effort to just make features we already have work again with terrains.

**Comment by dkniffin** [comment]
For a suitable data source, I know of a couple. There's [Mapbox terrain](https://www.mapbox.com/developers/vector-tiles/mapbox-terrain/#Overview), which is already in vector format. I haven't used it much, but I believe it's good, and being improved. There's also [SRTM](http://www2.jpl.nasa.gov/srtm/), which would require some pre-processing, because it's not in vector format to begin with.

**Comment by rbuch703** [comment]
Mapbox terrain does not seem suitable to me. From your link it seems they do not provide height information directly, but only provide hillshading and contour lines. Hillshading is - technically speaking - a gradient map of the height information, but cannot easily be converted to an actual height map. And the page itself states that
> At zoom levels above 14 you may want to blur, fade, or completely hide the hillshade layer as the resolution of the data is not enough to hold up at the largest scales.

So it does not have enough detail for exactly those zoom levels where we need it.

The provided contour lines may be usable, but they are difficult to work with. They seem to have a height resolution of 10m, which may be enough. But deriving height information from contour line *tiles* seems rather difficult, because in each tile you only have height information *between* two contour lines. So, from a tile itself we cannot get the height outside the outmost contour line.

I'd actually prefer the SRTM data, because it's - theoretically - easier to work with: It already contains the height information in a regular grid. It's pretty easy to convert this to tiles the size we need, and then to create terrain geometry from each tile. But there are two issues with SRTM that we cannot currently solve:

1. The data set is huge. The raw data should be about 2TB in size, and tiling this to our needs would likely increase the size. I don't think we have a server that can hold and serve that much data.
2. We need a terrain model ("DTM"), but the SRTM data is an elevation model ("DEM"). So for points covered by buildings or trees, SRTM measured the elevation of the *top* of the tree/building, while we would need the elevation at the *bottom*.

Ideally, someone would host a tiled DTM that we could use for free. But I'm not aware of any such provider.

**Comment by dkniffin** [comment]
Found another source: https://cesiumjs.org/data-and-assets/terrain/stk-world-terrain.html, and it might be worth checking out the ones mentioned here: http://gis.stackexchange.com/questions/7860/are-there-open-access-terrain-tiles-with-a-permissive-license-like-osm

**Comment by kekscom** [comment]
From some reading I found not much what Cesium could help us.
Mapbox ist listing some interesting things https://www.mapbox.com/tilemill/docs/guides/terrain-data/
I'm also in touch with some experts about setting this up.

**Comment by rbuch703** [comment]
The STK World Terrain from cesiumjs.org seems to be a good data source to me. It's free, has decent resolution, full planet coverage, is tiled, already meshed, and additionally (seemingly) optimized to minimize the amount of geometry.

On the down side, their tiling is not the same as ours (lat/lng vs. Web Mercator quadtrees) making texturing the terrain difficult. And their file format is quite complex, so implementing it will take some time. But all in all it should be usable.

**Comment by kekscom** [comment]
I'm worried about relying on AGI and it's conditions for this.
There is good chance we get good data + expertise from other sources.

Can we go with a rendering prototype to find out what are our data requirements?
For solving terrain tile pitfalls, I found this a good read: http://www.zephyrosanemos.com/#heading2

**Comment by rbuch703** [comment]
Yes, we can start with a prototype. We have to keep in mind, though, that quite a big part of the render code depends on what the actual data is structured like (tiles vs. bounds queries, mesh vs. points vs. grid, projection, file format, ...). So we shouldn't spend too much time on the prototype before we are sure what actual data source to use.

Just to get us started I generated a random terrain, saved it as color-coded `png` tiles, and created a mipmap-hierarchy on top of it. You can view the tiles at http://rbuch703.de/height/ (tile URLs are http://rbuch703.de/tiles/height/{z}/{x}/{y}.png ). This terrain obviously does not relate in any way to actual surface heights on earth. But it's available now and so can get us started. The terrain covers the whole earth via the usual slippy tiles naming scheme (the terrain features repeat over the Earth' surface, but that's transparent to the data user), so these terrain tiles cover exactly the same areas as the corresponding basemap tiles that we'll probably want to use to texture the terrain.

**Comment by kekscom** [comment]
https://mapzen.com/blog/elevation/

**Comment by rbuch703** [comment]
Now **that** is the kind of terrain data source I was hoping for!

I created some basic code to render this terrain in the `terrain` branch.

**Comment by rbuch703** [comment]
Ok, so here are the lessons learned from this early implementation of terrain rendering. This is not to complain about the difficulties, but rather to collect the questions that we need to answer for terrain rendering to work smoothly.

- for terrain, we'd have to restructure our internal data representation: the basemap now will no longer be an independent entity, but will be the textures the terrain is rendered with. Likewise, buildings cannot any longer be placed independently, since their vertical position depends on the terrain underneath them.
- fortunately, the Mapbox basemap, OSMBuildings GeoJSON buildings and Mapzen terrain tiles all use the same map projection and tile naming scheme. So, a given tile covers exactly the same geographical area in each data source (that's not true, for example, for the Caesium terrain data)
- the Mapzen terrain may not work as-is on mobile devices. It seems that mobile browsers manipulate image colors on loading the images: they appear to apply some kind of dithering/noise, probably to make it less obvious that mobile devices usually only have 16bit of color resolution. In some experiments of mine (unrelated to OSMBuidings), pixel color values were changed by as much as +/- 4/256 for each color channel by mobile browsers. For the Mapzen color-coded terrain heights, a random change of 4 in the red color channel would translate to a random, non-uniform height change of more than 1000 meters! So if that behavior is still present in mobile browsers, we cannot rely on them to decode color-coded terrain images for us.
- we'll have to "slave" the basemap and buildings to the terrain: terrain needs to be loaded first, because buildings and basemap cannot be rendered/placed without it (alternatively, we can start with dummy terrain to render the basemap and place the buildings on, but then we'd have to adjust them again once the actual terrain is loaded)
- alignment is going to be tough: ideally, basemap tiles, building tiles and terrain tiles would all cover the same area so that we can texture a terrain tile with a single basemap tile, and place all buildings from a single building tile based on the heights from a single terrain tile. Unfortunately, that's not going to happen: 
  - the basemap needs to be of far higher resolution than the terrain below to be legible. And since a single terrain tile cover quite a large area of the screen space, we are (already) using several basemap tiles of even different zoom levels to cover a single terrain tile. I have no idea yet how to texture the geometry of that single terrain tile with an arbitrary set of basemap textures without having to split the terrain tile geometry whenever the set of used basemap tiles changes.
  - for buildings, we could get away with always loading building tiles that *nominally* cover the same geographical area as the corresponding terrain tiles. This way, it would *seem* to be straight-forward to determine the vertical placement of each building solely from the terrain of the same tile. *But*, building tiles cover more area than they let on: A building tile will completely contain all buildings that *at least in part* lie in the given tile. This includes all buildings crossing into neighboring tiles, and multipolygons that represent a set of buildings, of which all but one may lie completely outside of the tile. So when we attempt to vertically place a building, we may realize that not only do we need terrain information from a different terrain tile, but we may realize that that tile has not even be (scheduled to be) loaded. I don't yet have a good idea for a software architecture that would solve this.
- for areas that lie up to about 300m above sea level, the camera system is probably fine as-is. But beyond that, so adjustments would be necessary: Currently, zooming in by a single zoom level translates to getting twice as close to *sea level*. That's sensible if basemap and buildings are actually located there, but will be highly confusing behavior the higher above sea level the geometry is.

**Comment by kekscom** [comment]
First of all, thanks for all the effort investigating this.
A fair amount of issues could be solved by involving the backend.
I could imagine, to align terrain tile sizes with building tiles. Maybe even pre-calculate elevation on features overlapping tile borders.
Also proxying tiles terrain with a different mime type or even combining data with buildings is a realistic option.
From backend side, I'm happy to prepare everything required.

Do you think it is feasible to implement, given your amount of spare time? Does it technically make sense?

**Comment by rbuch703** [comment]
I definitely won't be able to implement all of this in the forseeable future. I could start, but there would likely be a lot of issues left that affect the user experience. This is probably not a good situation to be in: we would give the world the idea that terrain rendering could be worth having, but at the same time for a long time wouldn't be able to actually provide a high-quality implementation. So we'd get a lot of disappointed users.

But I think that your second question is even more important. I don't think it would currently make technical sense to implement all this in OSMBuildings. The changes required are huge. And even when we manage to implement it, we'd by then effectively have written a Cesium clone (which the world probably doesn't need), and our code complexity would have increased quite a bit, making implementing further features all the more complex and time-consuming.  

So I wouldn't implement terrain rendering at this point, unless there is a concrete and financially well-supported interest out there that justifies this effort. Otherwise, I'd rather spend time on other features. For example, having an ego-perspective ("looking **from** position X") camera system in *addition* to the current "looking **at** map position X" would be far easier and yet would provide quite a bit of benefit.

**Comment by clement-igonet** [comment]
I did implement terrain elevation un Open Earth Project, Using heigthmap shader. Shader are very effective for that. I would be glad to help.

**Comment by clement-igonet** [comment]
Mapzen provides nice terrain service, but they will close their services soon, and join  mapbox.
