### ISSUE TITLE
Disappearing 3D-tiles on iOS

### ISSUE THREAD

**Issue by wallb** [OSMBuildings/OSMBuildings#49]
When I go to osmbuildings.org using safari on iOS (9.3) the 3D objects within individual tiles disappears/appears as I translate, rotate or zoom the map. Is it a known issue? Has anyone investigated as to why or have any ideas? It seems to also affect OBJects I add, i,e they seem to be clipped at tile borders as well.
![osmbuildings_ios](https://cloud.githubusercontent.com/assets/512856/14123239/f092de0c-f5ff-11e5-8020-d01b5f13095c.png)

**Comment by kekscom** [comment]
Notice: mobile Safari, perhaps a memory issue. Checking on iPad vs. iPhone
I'd like to involve @rbuch703 as well.

**Comment by kekscom** [comment]
Looks more like GL extension issues, perhaps even some math precision.
@wallb what device are you using?

## Tests

### Mac Safari 9.0.3

All fine here

### Mobile Safari on iPad 4 with iOS 9.2

http://osmbuildings.org is flickering whole tiles on any interaction
looks like even SSAO is in place but polygons are missing or broken.
no console messages

Older version (pre Shadows) http://codepen.io/osmbuildings/pen/avXGJy
Empty map. Very rarely few broken building fragments appear.
no console messages

### Mobile Safari on iPhone 5s with iOS 9.2

http://osmbuildings.org is flickering exactly like on iPad
no console messages

Older version (pre Shadows) http://codepen.io/osmbuildings/pen/avXGJy is perfectly fine here.

**Comment by wallb** [comment]
My initial screenshot was taken on an iPad 3 running mobile Safari on iOS 9.3.

The screenshot below is taken on a Samsung Galaxy s6 edge+ running Chrome (49.2623.105) on Android 6.01 (image is reduced in size).

![osmbuildings_galaxy_s6edge](https://cloud.githubusercontent.com/assets/512856/14135920/70f337e4-f660-11e5-811d-5a5afaaab5ca.png)

**Comment by rbuch703** [comment]
Judging from the screenshots, this looks as if we are not doing anything wrong in particular, but are simply overstressing those mobile GPUs. Note that the missing geometry tiles are square **on screen**, while OSMBuildings never renders only half of any wall (it actually sends the whole geometry of a single **map** tile to then GPU as a single chunk). The observed behavior is consistent with mobile GPUs to render a scene in tiles (e.g. 64x64 pixels) instead of rendering the whole screen at once (as desktop GPUs do). It seems those GPUs are running out of memory and thus decide to drop some tiles.

The first simple fix would be to detect mobile GPUs based on their User Agents and to disable memory-intensive effects on them. In particular,  AFAIR shadow mapping currently uses a 2048x2048 color texture plus depth buffer, requiring 32MB of memory alone.

In the long run, we should dynamically adjust the shadow map size with screen resolution and perspective, and should look into sharing the depth buffer and potentially even the color buffer between effects (shadow mapping, SSAO, blurring, etc.) to reduce memory consumption.

**Comment by wallb** [comment]
The problem remains when disabling shadows and enabling fastMode. When rotating the map it looks like it is complete tiles that "disappears", i.e. no longer screen aligned blocks.

However, the problem seem to go away or at least be greatly reduced by pushing the near and far clip planes closer together. They are set at 1 and 7500 respectively (I think) and when changing them to 100 and 5500 (or something) it looks much better. But then close objects might be visibly clipped when intersecting the near plane. Maybe they could be dynamically set (optimized) based on parameters like fog distance, zoom and tilt.

**Comment by rbuch703** [comment]
@wallb I see, that indeed rules out tiling GPUs as the culprit. Based on what you were saying my next guest would be that this is caused by the polygon offset we use while rendering the basemap tiles (not the geometry tiles though). Could you try removing the calls to GL.polygon Offset() and see how the output looks? If I'm right, this should cause z-fighting artifacts between basemap tiles of different zoom levels, but 3D buildings should not disappear anymore.

**Comment by wallb** [comment]
I have continued looking into the use and precision of the depth buffer. On the iPad 3 (mobile safari, iOS 9.3) `context.getParameter(context.DEPTH_BITS)` returns 24. This is the same as in desktop browsers where there are no problem of disappearing buildings. I think the culprit is the use of
```
#ifdef GL_ES
  precision mediump float;
#endif
````
in the vertex shaders. When changing them to
```
precision highp float;
```
the full 24 bits are used and the issue seem to be resolved. I guess that on desktop the GLSL precision is disregarded and 32-bits are used in vertex calculations while on mobile the mediump specifier turns the depth buffer into effectively 16 bits. I haven't checked how this change affects performance though.

**Comment by rbuch703** [comment]
Based on your findings, I changed the float precision to `highp` in all vertex shaders in the 'precision' branch (`highp` is actually the default for vertex shaders, but setting it explicitly felt more expressive and more likely to prevent future errors). Could you verify that this solves the issue before I merge the changes into 'master'?

**Comment by rbuch703** [comment]
@wallb just as a side-note: your explanation for why the error occurs is slightly off: `highp` (and also `mediump`and `lowp`) are not fixed precisions, but only guarantee a minimum precision, with implementations being free to use a higher precision. In WebGL/OpenGL ES 2, `highp` actually only guarantees floats with 16 bits and a range of [-2^62 ... 2^62]. Fortunately desktop and recent mobile GPUs both provide higher precision, usually conforming to 32 bit floats. 

Now for `mediump`, the standard only mandates 10 bit floats, and here the actual formats differ between mobile and desktop GPUs: While desktop GPUs seem to provide 32 bit floats even for `mediump`, even recent mobile GPUs seem to opt for a lower precision (though apparently not as low as the standard would allow). So desktop GPUs do not *disregard* the `mediump` qualifier, but simply *opt* for a precision not only higher than the standard requires, but also higher than what mobile GPUs provide - all in accordance with the standard.

In any case, I failed to account for any of this while writing/modifying the shaders :-/ .

**Comment by wallb** [comment]
@rbuch703 thanks for clearing that up. Yes, the issue seems to be resolved by the changes in the 'precision' branch.

**Comment by kekscom** [comment]
Working fine.
@wallb & @rbuch703 thank you very much for analyzing this!
